#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 55
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 15

enum {
  anon_sym_DOLLARMODULE = 1,
  anon_sym_SEMI = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_EQ = 5,
  anon_sym_COMMA = 6,
  anon_sym_COLON = 7,
  sym_str_br_l = 8,
  sym_str_br_r = 9,
  sym_fun_br_l = 10,
  sym_fun_br_r = 11,
  sym_q_symbol = 12,
  sym_e_var = 13,
  sym_s_var = 14,
  sym_t_var = 15,
  sym_id = 16,
  sym_comment = 17,
  sym_source_file = 18,
  sym_module = 19,
  sym_function = 20,
  sym_sentence = 21,
  sym_condition = 22,
  sym__pattern_obj = 23,
  sym__pattern_obj_br = 24,
  sym__obj = 25,
  sym__obj_br = 26,
  sym__obj_fn = 27,
  sym__symbol = 28,
  aux_sym_source_file_repeat1 = 29,
  aux_sym_function_repeat1 = 30,
  aux_sym_sentence_repeat1 = 31,
  aux_sym_sentence_repeat2 = 32,
  aux_sym_sentence_repeat3 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOLLARMODULE] = "$MODULE",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [sym_str_br_l] = "str_br_l",
  [sym_str_br_r] = "str_br_r",
  [sym_fun_br_l] = "fun_br_l",
  [sym_fun_br_r] = "fun_br_r",
  [sym_q_symbol] = "q_symbol",
  [sym_e_var] = "e_var",
  [sym_s_var] = "s_var",
  [sym_t_var] = "t_var",
  [sym_id] = "id",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_module] = "module",
  [sym_function] = "function",
  [sym_sentence] = "sentence",
  [sym_condition] = "condition",
  [sym__pattern_obj] = "_pattern_obj",
  [sym__pattern_obj_br] = "_pattern_obj_br",
  [sym__obj] = "_obj",
  [sym__obj_br] = "_obj_br",
  [sym__obj_fn] = "_obj_fn",
  [sym__symbol] = "_symbol",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_repeat1] = "function_repeat1",
  [aux_sym_sentence_repeat1] = "sentence_repeat1",
  [aux_sym_sentence_repeat2] = "sentence_repeat2",
  [aux_sym_sentence_repeat3] = "sentence_repeat3",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOLLARMODULE] = anon_sym_DOLLARMODULE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_str_br_l] = sym_str_br_l,
  [sym_str_br_r] = sym_str_br_r,
  [sym_fun_br_l] = sym_fun_br_l,
  [sym_fun_br_r] = sym_fun_br_r,
  [sym_q_symbol] = sym_q_symbol,
  [sym_e_var] = sym_e_var,
  [sym_s_var] = sym_s_var,
  [sym_t_var] = sym_t_var,
  [sym_id] = sym_id,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_module] = sym_module,
  [sym_function] = sym_function,
  [sym_sentence] = sym_sentence,
  [sym_condition] = sym_condition,
  [sym__pattern_obj] = sym__pattern_obj,
  [sym__pattern_obj_br] = sym__pattern_obj_br,
  [sym__obj] = sym__obj,
  [sym__obj_br] = sym__obj_br,
  [sym__obj_fn] = sym__obj_fn,
  [sym__symbol] = sym__symbol,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_repeat1] = aux_sym_function_repeat1,
  [aux_sym_sentence_repeat1] = aux_sym_sentence_repeat1,
  [aux_sym_sentence_repeat2] = aux_sym_sentence_repeat2,
  [aux_sym_sentence_repeat3] = aux_sym_sentence_repeat3,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOLLARMODULE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_str_br_l] = {
    .visible = true,
    .named = true,
  },
  [sym_str_br_r] = {
    .visible = true,
    .named = true,
  },
  [sym_fun_br_l] = {
    .visible = true,
    .named = true,
  },
  [sym_fun_br_r] = {
    .visible = true,
    .named = true,
  },
  [sym_q_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_e_var] = {
    .visible = true,
    .named = true,
  },
  [sym_s_var] = {
    .visible = true,
    .named = true,
  },
  [sym_t_var] = {
    .visible = true,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym__pattern_obj] = {
    .visible = false,
    .named = true,
  },
  [sym__pattern_obj_br] = {
    .visible = false,
    .named = true,
  },
  [sym__obj] = {
    .visible = false,
    .named = true,
  },
  [sym__obj_br] = {
    .visible = false,
    .named = true,
  },
  [sym__obj_fn] = {
    .visible = false,
    .named = true,
  },
  [sym__symbol] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentence_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentence_repeat3] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_conditions = 1,
  field_function = 2,
  field_module = 3,
  field_name = 4,
  field_pattern = 5,
  field_rewrite = 6,
  field_sentence = 7,
  field_test = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_conditions] = "conditions",
  [field_function] = "function",
  [field_module] = "module",
  [field_name] = "name",
  [field_pattern] = "pattern",
  [field_rewrite] = "rewrite",
  [field_sentence] = "sentence",
  [field_test] = "test",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 1},
  [9] = {.index = 10, .length = 1},
  [10] = {.index = 11, .length = 2},
  [11] = {.index = 13, .length = 2},
  [12] = {.index = 15, .length = 2},
  [13] = {.index = 17, .length = 2},
  [14] = {.index = 19, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_module, 0},
  [1] =
    {field_function, 1},
    {field_module, 0},
  [3] =
    {field_name, 1},
  [4] =
    {field_name, 0},
    {field_sentence, 2},
  [6] =
    {field_rewrite, 1},
  [7] =
    {field_pattern, 2},
  [8] =
    {field_test, 1},
  [9] =
    {field_pattern, 0},
  [10] =
    {field_conditions, 0},
  [11] =
    {field_pattern, 3},
    {field_test, 1},
  [13] =
    {field_pattern, 0},
    {field_rewrite, 2},
  [15] =
    {field_conditions, 1},
    {field_pattern, 0},
  [17] =
    {field_conditions, 0},
    {field_rewrite, 2},
  [19] =
    {field_conditions, 1},
    {field_pattern, 0},
    {field_rewrite, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '$') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(1);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == ')') ADVANCE(26);
      if (lookahead == ',') ADVANCE(23);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '<') ADVANCE(27);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '>') ADVANCE(28);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\f') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'D') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 'L') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'M') ADVANCE(12);
      if (lookahead == 'e') ADVANCE(5);
      if (lookahead == 's') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == 'O') ADVANCE(8);
      END_STATE();
    case 13:
      if (lookahead == 'U') ADVANCE(10);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOLLARMODULE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_str_br_l);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_str_br_r);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_fun_br_l);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_fun_br_r);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_q_symbol);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_e_var);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_e_var);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_s_var);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_s_var);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_t_var);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_t_var);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOLLARMODULE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_str_br_l] = ACTIONS(1),
    [sym_str_br_r] = ACTIONS(1),
    [sym_fun_br_l] = ACTIONS(1),
    [sym_fun_br_r] = ACTIONS(1),
    [sym_q_symbol] = ACTIONS(1),
    [sym_e_var] = ACTIONS(1),
    [sym_s_var] = ACTIONS(1),
    [sym_t_var] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(54),
    [sym_module] = STATE(46),
    [anon_sym_DOLLARMODULE] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym_sentence] = STATE(3),
    [sym_condition] = STATE(47),
    [sym__pattern_obj] = STATE(6),
    [sym__pattern_obj_br] = STATE(6),
    [sym__symbol] = STATE(6),
    [aux_sym_function_repeat1] = STATE(3),
    [aux_sym_sentence_repeat1] = STATE(6),
    [aux_sym_sentence_repeat2] = STATE(47),
    [anon_sym_RBRACE] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(11),
    [sym_str_br_l] = ACTIONS(13),
    [sym_q_symbol] = ACTIONS(15),
    [sym_e_var] = ACTIONS(15),
    [sym_s_var] = ACTIONS(15),
    [sym_t_var] = ACTIONS(15),
    [sym_id] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [3] = {
    [sym_sentence] = STATE(3),
    [sym_condition] = STATE(47),
    [sym__pattern_obj] = STATE(6),
    [sym__pattern_obj_br] = STATE(6),
    [sym__symbol] = STATE(6),
    [aux_sym_function_repeat1] = STATE(3),
    [aux_sym_sentence_repeat1] = STATE(6),
    [aux_sym_sentence_repeat2] = STATE(47),
    [anon_sym_RBRACE] = ACTIONS(17),
    [anon_sym_EQ] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(22),
    [sym_str_br_l] = ACTIONS(25),
    [sym_q_symbol] = ACTIONS(28),
    [sym_e_var] = ACTIONS(28),
    [sym_s_var] = ACTIONS(28),
    [sym_t_var] = ACTIONS(28),
    [sym_id] = ACTIONS(28),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      sym_str_br_l,
    ACTIONS(36), 1,
      sym_fun_br_l,
    ACTIONS(31), 4,
      anon_sym_SEMI,
      anon_sym_COLON,
      sym_str_br_r,
      sym_fun_br_r,
    ACTIONS(39), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(4), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [30] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_EQ,
    ACTIONS(11), 1,
      anon_sym_COMMA,
    ACTIONS(13), 1,
      sym_str_br_l,
    STATE(2), 2,
      sym_sentence,
      aux_sym_function_repeat1,
    STATE(47), 2,
      sym_condition,
      aux_sym_sentence_repeat2,
    STATE(6), 4,
      sym__pattern_obj,
      sym__pattern_obj_br,
      sym__symbol,
      aux_sym_sentence_repeat1,
    ACTIONS(15), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [64] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_COMMA,
    ACTIONS(13), 1,
      sym_str_br_l,
    ACTIONS(42), 1,
      anon_sym_EQ,
    STATE(44), 2,
      sym_condition,
      aux_sym_sentence_repeat2,
    STATE(19), 4,
      sym__pattern_obj,
      sym__pattern_obj_br,
      sym__symbol,
      aux_sym_sentence_repeat1,
    ACTIONS(44), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [94] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_SEMI,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(52), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(8), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [121] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    ACTIONS(56), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(4), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [148] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(58), 1,
      anon_sym_SEMI,
    ACTIONS(56), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(4), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [175] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(60), 1,
      sym_fun_br_r,
    ACTIONS(56), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(4), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [202] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(62), 1,
      anon_sym_SEMI,
    ACTIONS(56), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(4), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [229] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(64), 1,
      anon_sym_SEMI,
    ACTIONS(66), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(9), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [256] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(68), 1,
      anon_sym_SEMI,
    ACTIONS(70), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(20), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [283] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(72), 1,
      anon_sym_COLON,
    ACTIONS(74), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(21), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [310] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(76), 1,
      sym_fun_br_r,
    ACTIONS(78), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(10), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [337] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(80), 1,
      sym_str_br_r,
    ACTIONS(56), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(4), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [364] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(82), 1,
      anon_sym_SEMI,
    ACTIONS(84), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(11), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [391] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(86), 1,
      sym_str_br_r,
    ACTIONS(88), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(16), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [418] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      sym_str_br_l,
    ACTIONS(90), 3,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_str_br_r,
    STATE(19), 4,
      sym__pattern_obj,
      sym__pattern_obj_br,
      sym__symbol,
      aux_sym_sentence_repeat1,
    ACTIONS(95), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [443] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(98), 1,
      anon_sym_SEMI,
    ACTIONS(56), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(4), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [470] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_str_br_l,
    ACTIONS(50), 1,
      sym_fun_br_l,
    ACTIONS(100), 1,
      anon_sym_COLON,
    ACTIONS(56), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
    STATE(4), 5,
      sym__obj,
      sym__obj_br,
      sym__obj_fn,
      sym__symbol,
      aux_sym_sentence_repeat3,
  [497] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_str_br_l,
    ACTIONS(102), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    STATE(19), 4,
      sym__pattern_obj,
      sym__pattern_obj_br,
      sym__symbol,
      aux_sym_sentence_repeat1,
    ACTIONS(44), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [521] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_str_br_l,
    ACTIONS(104), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    STATE(19), 4,
      sym__pattern_obj,
      sym__pattern_obj_br,
      sym__symbol,
      aux_sym_sentence_repeat1,
    ACTIONS(44), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [545] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_str_br_l,
    ACTIONS(106), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    STATE(22), 4,
      sym__pattern_obj,
      sym__pattern_obj_br,
      sym__symbol,
      aux_sym_sentence_repeat1,
    ACTIONS(108), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [569] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_str_br_l,
    ACTIONS(110), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    STATE(23), 4,
      sym__pattern_obj,
      sym__pattern_obj_br,
      sym__symbol,
      aux_sym_sentence_repeat1,
    ACTIONS(112), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [593] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 11,
      anon_sym_SEMI,
      anon_sym_COLON,
      sym_str_br_l,
      sym_str_br_r,
      sym_fun_br_l,
      sym_fun_br_r,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [610] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_str_br_l,
    ACTIONS(116), 1,
      sym_str_br_r,
    STATE(19), 4,
      sym__pattern_obj,
      sym__pattern_obj_br,
      sym__symbol,
      aux_sym_sentence_repeat1,
    ACTIONS(44), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [633] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 11,
      anon_sym_SEMI,
      anon_sym_COLON,
      sym_str_br_l,
      sym_str_br_r,
      sym_fun_br_l,
      sym_fun_br_r,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [650] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 11,
      anon_sym_SEMI,
      anon_sym_COLON,
      sym_str_br_l,
      sym_str_br_r,
      sym_fun_br_l,
      sym_fun_br_r,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [667] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_str_br_l,
    ACTIONS(122), 1,
      sym_str_br_r,
    STATE(27), 4,
      sym__pattern_obj,
      sym__pattern_obj_br,
      sym__symbol,
      aux_sym_sentence_repeat1,
    ACTIONS(124), 5,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [690] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 11,
      anon_sym_SEMI,
      anon_sym_COLON,
      sym_str_br_l,
      sym_str_br_r,
      sym_fun_br_l,
      sym_fun_br_r,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [707] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 9,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_str_br_l,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [722] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 9,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_str_br_l,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [737] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 9,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_str_br_l,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [752] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 9,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_str_br_l,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [767] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 9,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_str_br_l,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [782] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 9,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_str_br_l,
      sym_str_br_r,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [797] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 9,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_str_br_l,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [812] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 9,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_str_br_l,
      sym_str_br_r,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [827] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 9,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_str_br_l,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [842] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 9,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      sym_str_br_l,
      sym_q_symbol,
      sym_e_var,
      sym_s_var,
      sym_t_var,
      sym_id,
  [857] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
    ACTIONS(150), 1,
      sym_id,
    STATE(42), 2,
      sym_function,
      aux_sym_source_file_repeat1,
  [871] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_EQ,
    ACTIONS(155), 1,
      anon_sym_COMMA,
    STATE(43), 2,
      sym_condition,
      aux_sym_sentence_repeat2,
  [885] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_COMMA,
    ACTIONS(158), 1,
      anon_sym_EQ,
    STATE(43), 2,
      sym_condition,
      aux_sym_sentence_repeat2,
  [899] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      ts_builtin_sym_end,
    ACTIONS(162), 1,
      sym_id,
    STATE(42), 2,
      sym_function,
      aux_sym_source_file_repeat1,
  [913] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym_id,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
    STATE(45), 2,
      sym_function,
      aux_sym_source_file_repeat1,
  [927] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_EQ,
    STATE(43), 2,
      sym_condition,
      aux_sym_sentence_repeat2,
  [941] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(15), 1,
      sym__symbol,
    ACTIONS(168), 2,
      sym_q_symbol,
      sym_id,
  [952] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 2,
      ts_builtin_sym_end,
      sym_id,
  [960] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 2,
      ts_builtin_sym_end,
      sym_id,
  [968] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_SEMI,
  [975] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
  [982] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym_id,
  [989] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 30,
  [SMALL_STATE(6)] = 64,
  [SMALL_STATE(7)] = 94,
  [SMALL_STATE(8)] = 121,
  [SMALL_STATE(9)] = 148,
  [SMALL_STATE(10)] = 175,
  [SMALL_STATE(11)] = 202,
  [SMALL_STATE(12)] = 229,
  [SMALL_STATE(13)] = 256,
  [SMALL_STATE(14)] = 283,
  [SMALL_STATE(15)] = 310,
  [SMALL_STATE(16)] = 337,
  [SMALL_STATE(17)] = 364,
  [SMALL_STATE(18)] = 391,
  [SMALL_STATE(19)] = 418,
  [SMALL_STATE(20)] = 443,
  [SMALL_STATE(21)] = 470,
  [SMALL_STATE(22)] = 497,
  [SMALL_STATE(23)] = 521,
  [SMALL_STATE(24)] = 545,
  [SMALL_STATE(25)] = 569,
  [SMALL_STATE(26)] = 593,
  [SMALL_STATE(27)] = 610,
  [SMALL_STATE(28)] = 633,
  [SMALL_STATE(29)] = 650,
  [SMALL_STATE(30)] = 667,
  [SMALL_STATE(31)] = 690,
  [SMALL_STATE(32)] = 707,
  [SMALL_STATE(33)] = 722,
  [SMALL_STATE(34)] = 737,
  [SMALL_STATE(35)] = 752,
  [SMALL_STATE(36)] = 767,
  [SMALL_STATE(37)] = 782,
  [SMALL_STATE(38)] = 797,
  [SMALL_STATE(39)] = 812,
  [SMALL_STATE(40)] = 827,
  [SMALL_STATE(41)] = 842,
  [SMALL_STATE(42)] = 857,
  [SMALL_STATE(43)] = 871,
  [SMALL_STATE(44)] = 885,
  [SMALL_STATE(45)] = 899,
  [SMALL_STATE(46)] = 913,
  [SMALL_STATE(47)] = 927,
  [SMALL_STATE(48)] = 941,
  [SMALL_STATE(49)] = 952,
  [SMALL_STATE(50)] = 960,
  [SMALL_STATE(51)] = 968,
  [SMALL_STATE(52)] = 975,
  [SMALL_STATE(53)] = 982,
  [SMALL_STATE(54)] = 989,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(13),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(14),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(30),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(6),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_repeat3, 2),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat3, 2), SHIFT_REPEAT(18),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat3, 2), SHIFT_REPEAT(48),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat3, 2), SHIFT_REPEAT(4),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2), SHIFT_REPEAT(30),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2), SHIFT_REPEAT(19),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, .production_id = 6),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 4, .production_id = 10),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 2),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, .production_id = 7),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__obj_fn, 3),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__obj_fn, 4),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__obj_br, 3),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__obj_br, 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 3, .production_id = 9),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 5, .production_id = 14),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 2),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 3, .production_id = 5),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 4, .production_id = 13),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pattern_obj_br, 2),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 4, .production_id = 12),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pattern_obj_br, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 3, .production_id = 8),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 4, .production_id = 11),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(52),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_repeat2, 2),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat2, 2), SHIFT_REPEAT(14),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, .production_id = 2),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, .production_id = 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 3, .production_id = 3),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4, .production_id = 4),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [180] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_refal(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
